name:                amqp-worker
version:             0.3.1
github:              "seanhess/amqp-worker"
license:             BSD3
author:              "Sean Hess"
maintainer:          "seanhess@gmail.com"
copyright:           "Orbital Labs"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/seanhess/server#readme>

dependencies:
  - base >=4.9 && <5
  - aeson
  - amqp
  - bytestring
  - exceptions
  - data-default
  - microlens
  - monad-control
  - monad-loops
  - mtl
  - resource-pool
  - split
  - text
  - transformers-base

library:
  source-dirs: src

executables:
  example:
    main:                Example.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - amqp-worker

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - server
