name:                amqp-worker
version:             2.0.0
github:              "seanhess/amqp-worker"
author:              "Sean Hess"
maintainer:          "seanhess@gmail.com"
copyright:           "Orbital Labs"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Type-safe AMQP workers
category:            Network

description:         Please see the README on GitHub at <https://github.com/seanhess/amqp-worker#readme>

dependencies:
  - base >=4.9 && <5
  - aeson >=2.0 && <2.3
  - amqp >=0.20 && <1
  - bytestring >=0.11 && <0.12
  - exceptions >=0.10 && <0.11
  - monad-loops >=0.4 && <0.5
  - mtl >=2.2 && <2.3
  - resource-pool >=0.3 && <0.5
  - text >=1.2 && <1.3

library:
  source-dirs: src

executables:
  example:
    main:                Example.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - amqp-worker

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - amqp-worker
